name: Deploy version of jar

on:
  push:
    branches:
      - [master, git_workflow]
    paths:
      - camouflage-beam/
      - camouflage-core/
      - camouflage-spark/
  workflow_dispatch:
    inputs:
      tags:
        description: 'Test scenario tags'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    # - name: Checkout tools repo
    #   uses: actions/checkout@v2
    #   with:
    #     repository: cldcvr/datapipes-mvn-repo
    #     path: datapipes-mvn-repo
    
    - name: Build snapshot with Maven
      run: mvn clean install --file camouflage/pom.xml

    - name: Find spark jar file
      id: spark_jar_file
      run: |
         spark_jar_path=`find . -name 'camouflage-spark-*-SNAPSHOT.jar'`
         echo "::set-output name=SPARK_JAR_LOCATION::$spark_jar_path"
         spark_jar_name=`echo $spark_jar_path | rev | cut -d'/' -f1 | rev`
         echo $spark_jar_name
         spark_jar_version=`echo $spark_jar_name | rev | cut -d'-' -f2 | rev`
         echo "::set-output name=SPARK_JAR_VERSION::$spark_jar_version"

    - name: Find beam jar file
      id: beam_jar_file
      run: |
         beam_jar_path=`find . -name 'camouflage-beam-*-SNAPSHOT.jar'`
         echo "::set-output name=BEAM_JAR_LOCATION::$beam_jar_path"
         beam_jar_name=`echo $beam_jar_path | rev | cut -d'/' -f1 | rev`
         echo $beam_jar_name
         beam_jar_version=`echo $beam_jar_name | rev | cut -d'-' -f2 | rev`
         echo "::set-output name=BEAM_JAR_VERSION::$beam_jar_version"  

    - name: Build version with Maven
      run: |
         mvn install:install-file -Dfile=${{ steps.jar_file.outputs.SPARK_JAR_LOCATION }}  -DgroupId=camouflage-spark -DartifactId=camouflage-spark -Dversion=${{ steps.jar_file.outputs.SPARK_JAR_VERSION }} -Dpackaging=jar -DgeneratePom=true -DlocalRepositoryPath=datapipes-mvn-repo/  -DcreateChecksum=true
         mvn install:install-file -Dfile=${{ steps.jar_file.outputs.BEAM_JAR_LOCATION }}  -DgroupId=camouflage-beam -DartifactId=camouflage-beam -Dversion=${{ steps.jar_file.outputs.BEAM_JAR_VERSION }} -Dpackaging=jar -DgeneratePom=true -DlocalRepositoryPath=datapipes-mvn-repo/  -DcreateChecksum=true

    - name: Commit jars to repo
      run: |
         git config --local user.email "action@github.com"
         git config --local user.name "GitHub Action"
         git commit -m "Release version ${{ steps.jar_file.outputs.SPARK_JAR_LOCATION }}" -a
    
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: repository