name: Deploy version of jar

on:
  push:
    branches:
      - [master, hash_fix]
    paths:
      - camouflage-beam/
      - camouflage-core/
      - camouflage-spark/
  workflow_dispatch:
    inputs:
      tags:
        description: 'Test scenario tags'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    - name: Checkout tools repo
      uses: actions/checkout@v2
      with:
        repository: cldcvr/datapipes-mvn-repo
        path: datapipes-mvn-repo
    
    - name: Build snapshot with Maven
      run: mvn clean install --file camouflage/pom.xml

    - name: Find spark jar file
      id: spark_jar_file
      run: |
         spark_jar_path=`find . -name 'camouflage-spark-*-SNAPSHOT.jar'`
         echo "::set-output name=SPARK_JAR_LOCATION::$spark_jar_path"
         spark_jar_name=`echo $spark_jar_path | rev | cut -d'/' -f1 | rev`
         echo $spark_jar_name
         spark_jar_version=`echo $spark_jar_name | rev | cut -d'-' -f2 | rev`
         echo "::set-output name=SPARK_JAR_VERSION::$spark_jar_version"
    - name: Build version with Maven
      run: |
         mvn install:install-file -Dfile=${{ steps.jar_file.outputs.SPARK_JAR_LOCATION }}  -DgroupId=camouflage-spark -DartifactId=camouflage-spark -Dversion=${{ steps.jar_file.outputs.SPARK_JAR_VERSION }} -Dpackaging=jar -DgeneratePom=true -DlocalRepositoryPath=datapipes-mvn-repo/  -DcreateChecksum=true

    - name: deploy jar to repo
      run |
         git checkout -b release_${{ steps.jar_file.outputs.SPARK_JAR_VERSION }}
         git add .
         git commit -m "release_version_${{ steps.jar_file.outputs.SPARK_JAR_VERSION }}"

       