name: Deploy version of jar

on:
  push:
    branches: [master, workflow]
    paths: [camouflage-beam/, camouflage-core/, camouflage-spark/]
  workflow_dispatch:
    inputs:
      tags:
        description: 'run workflow'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    
    - name: Build snapshot with Maven
      run: mvn clean install

    - name: Find spark jar file
      id: spark_jar_file
      run: |
         spark_jar_path=`find . -name 'camouflage-spark-*-SNAPSHOT.jar'`
         echo "::set-output name=SPARK_JAR_LOCATION::$spark_jar_path"
         spark_jar_name=`echo $spark_jar_path | rev | cut -d'/' -f1 | rev`
         echo $spark_jar_name
         spark_jar_version=`echo $spark_jar_name | rev | cut -d'-' -f2 | rev`
         echo "::set-output name=SPARK_JAR_VERSION::$spark_jar_version"

    - name: Find beam jar file
      id: beam_jar_file
      run: |
         beam_jar_path=`find . -name 'camouflage-beam-*-SNAPSHOT.jar'`
         echo "::set-output name=BEAM_JAR_LOCATION::$beam_jar_path"
         beam_jar_name=`echo $beam_jar_path | rev | cut -d'/' -f1 | rev`
         echo $beam_jar_name
         beam_jar_version=`echo $beam_jar_name | rev | cut -d'-' -f2 | rev`
         echo "::set-output name=BEAM_JAR_VERSION::$beam_jar_version"  

    - name: Build version with Maven
      run: |
         mvn install:install-file -Dfile=${{ steps.spark_jar_file.outputs.SPARK_JAR_LOCATION }}  -DgroupId=camouflage-spark -DartifactId=camouflage-spark -Dversion=${{ steps.spark_jar_file.outputs.SPARK_JAR_VERSION }} -Dpackaging=jar -DgeneratePom=true -DlocalRepositoryPath=../datapipes-mvn-repo/  -DcreateChecksum=true
         mvn install:install-file -Dfile=${{ steps.beam_jar_file.outputs.BEAM_JAR_LOCATION }}  -DgroupId=camouflage-beam -DartifactId=camouflage-beam -Dversion=${{ steps.beam_jar_file.outputs.BEAM_JAR_VERSION }} -Dpackaging=jar -DgeneratePom=true -DlocalRepositoryPath=../datapipes-mvn-repo/  -DcreateChecksum=true

    - name: Commit jars to repo
      run: |
         pwd
         git config user.email "action@github.com"
         git config user.name "action"
         git fetch
         git checkout -f repository
         cp -r ../datapipes-mvn-repo .
         git add .
         git commit -m "release version ${{ steps.spark_jar_file.outputs.SPARK_JAR_VERSION }}"
         git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 

       